api_platform:
    title: "Api for bileMo App"

    description: "Documentation for Api"

    version: "0.0.1"
    mapping:
        #for yaml
        paths: [ '%kernel.project_dir%/config/api_platform/resources' ]
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        api_keys:
            apiKey:
                name: Authorization
                type: header