App\Entity\Client:
  itemOperations:
    get:
      normalization_context:
        groups: [ 'client:item:get' ]
      security: 'is_granted("ROLE_ADMIN")'
  collectionOperations:
    register:
      method: POST
      input: App\Dto\CreateClient
      normalization_context:
        groups: [ 'user:item:get' ]
