App\Entity\Product:
  itemOperations:
    get:
      normalization_context:
        groups: ['product:item:get']
      security: 'is_granted("ROLE_USER")'
  collectionOperations:
    get:
      normalization_context:
        groups: ['product:collection:get']
      security: 'is_granted("ROLE_USER")'
