App\Entity\User:
  attributes:
    id:
      groups: ['user:item:get']
    lastName:
      groups: ['user:item:get', 'user:collection:post', 'user:collection:get', 'user:item:put']
    firstName:
      groups: ['user:item:get', 'user:collection:post', 'user:collection:get', 'user:item:put']
